// Org → official homepage and GitHub org.
// Used by the node detail page (header link pills) and ModelSpec
// (official-site link). Kept in one place so the two surfaces stay in sync.
//
// A missing entry means "no good generic link" — the UI should simply
// omit the link rather than guessing.

export const ORG_HOMEPAGE: Record<string, string> = {
  "OpenAI": "https://openai.com/",
  "Anthropic": "https://www.anthropic.com/",
  "Google": "https://ai.google/",
  "Google DeepMind": "https://deepmind.google/",
  "DeepMind": "https://deepmind.google/",
  "Google Brain": "https://research.google/teams/brain/",
  "Meta AI": "https://ai.meta.com/",
  "Microsoft": "https://www.microsoft.com/en-us/research/",
  "Mistral AI": "https://mistral.ai/",
  "Stability AI": "https://stability.ai/",
  "EleutherAI": "https://www.eleuther.ai/",
  "Cohere": "https://cohere.com/",
  "xAI": "https://x.ai/",
  "Alibaba": "https://qwen.ai/",
  "DeepSeek": "https://www.deepseek.com/",
  "Zhipu": "https://z.ai/",
  "01.AI": "https://www.01.ai/",
  "Baidu": "https://yiyan.baidu.com/",
  "Tencent": "https://hunyuan.tencent.com/",
  "Moonshot AI": "https://www.moonshot.cn/",
  "MiniMax": "https://www.minimax.io/",
  "ByteDance": "https://www.volcengine.com/",
  "Stepfun": "https://www.stepfun.com/",
  "Suno": "https://suno.com/",
  "Runway": "https://runwayml.com/",
  "Black Forest Labs": "https://blackforestlabs.ai/",
  "Databricks": "https://www.databricks.com/research",
  "Perplexity": "https://www.perplexity.ai/",
  "Kuaishou": "https://kling.kuaishou.com/",
  "Hugging Face": "https://huggingface.co/",
  "BigScience": "https://huggingface.co/bigscience",
  "Allen AI": "https://allenai.org/",
  "Salesforce": "https://www.salesforce.com/ai/",
  "Nvidia": "https://www.nvidia.com/en-us/ai/",
  "Apple": "https://machinelearning.apple.com/",
  "IBM": "https://research.ibm.com/artificial-intelligence",
  "Huawei": "https://www.huaweicloud.com/intl/en-us/product/pangu.html",
  "Xiaomi": "https://www.xiaomi.com/",
  "Ant Group": "https://www.antgroup.com/en/research",
  "Shanghai AI Lab": "https://www.shlab.org.cn/",
  "BAAI": "https://www.baai.ac.cn/english.html",
  "AI21 Labs": "https://www.ai21.com/",
  "Reka AI": "https://www.reka.ai/",
  "Adobe": "https://research.adobe.com/",
  "Amazon": "https://aws.amazon.com/ai/generative-ai/nova/",
  "Arc Institute": "https://arcinstitute.org/",
  "Boston Dynamics": "https://bostondynamics.com/",
  "Cartesia": "https://cartesia.ai/",
  "Cognition": "https://www.cognition.ai/",
  "ElevenLabs": "https://elevenlabs.io/",
  "Figure AI": "https://www.figure.ai/",
  "Ideogram": "https://ideogram.ai/",
  "Lightricks": "https://www.lightricks.com/",
  "Liquid AI": "https://www.liquid.ai/",
  "Luma AI": "https://lumalabs.ai/",
  "Midjourney": "https://www.midjourney.com/",
  "MIT": "https://www.csail.mit.edu/",
  "Physical Intelligence": "https://www.physicalintelligence.company/",
  "Pika Labs": "https://pika.art/",
  "Sesame": "https://www.sesame.com/",
  "Snowflake": "https://www.snowflake.com/en/product/features/cortex/",
  "Synthesia": "https://www.synthesia.io/",
  "Tesla": "https://www.tesla.com/AI",
  "Together AI": "https://www.together.ai/",
  "Ultralytics": "https://www.ultralytics.com/",
  "Unitree": "https://www.unitree.com/",
  "Voyage AI": "https://www.voyageai.com/",
  "Wayve": "https://wayve.ai/",
  "Writer": "https://writer.com/",
  "Hedra": "https://www.hedra.com/",
  "Hume AI": "https://hume.ai/",
  "Nari Labs": "https://nari-labs.com/",
  "Recraft": "https://www.recraft.ai/",
};

// Org → primary GitHub org used for open-weights / open-source releases.
// Only include orgs that actually publish model code / weights on GitHub.
// Closed-source labs (Anthropic, Midjourney, etc.) are intentionally absent.
export const ORG_GITHUB: Record<string, string> = {
  "OpenAI": "https://github.com/openai",
  "Google": "https://github.com/google-research",
  "Google DeepMind": "https://github.com/google-deepmind",
  "DeepMind": "https://github.com/google-deepmind",
  "Google Brain": "https://github.com/google-research",
  "Meta AI": "https://github.com/facebookresearch",
  "Microsoft": "https://github.com/microsoft",
  "Mistral AI": "https://github.com/mistralai",
  "Stability AI": "https://github.com/Stability-AI",
  "EleutherAI": "https://github.com/EleutherAI",
  "Cohere": "https://github.com/cohere-ai",
  "xAI": "https://github.com/xai-org",
  "Alibaba": "https://github.com/QwenLM",
  "DeepSeek": "https://github.com/deepseek-ai",
  "Zhipu": "https://github.com/THUDM",
  "01.AI": "https://github.com/01-ai",
  "Tencent": "https://github.com/Tencent",
  "Moonshot AI": "https://github.com/MoonshotAI",
  "MiniMax": "https://github.com/MiniMax-AI",
  "ByteDance": "https://github.com/bytedance",
  "Stepfun": "https://github.com/stepfun-ai",
  "Black Forest Labs": "https://github.com/black-forest-labs",
  "Databricks": "https://github.com/databricks",
  "Hugging Face": "https://github.com/huggingface",
  "BigScience": "https://github.com/bigscience-workshop",
  "Allen AI": "https://github.com/allenai",
  "Salesforce": "https://github.com/salesforce",
  "Nvidia": "https://github.com/NVIDIA",
  "Apple": "https://github.com/apple",
  "IBM": "https://github.com/IBM",
  "Shanghai AI Lab": "https://github.com/InternLM",
  "BAAI": "https://github.com/FlagAI-Open",
  "AI21 Labs": "https://github.com/AI21Labs",
  "Reka AI": "https://github.com/reka-ai",
  "Together AI": "https://github.com/togethercomputer",
  "Ultralytics": "https://github.com/ultralytics",
  "Unitree": "https://github.com/unitreerobotics",
  "Nari Labs": "https://github.com/nari-labs",
};
